version: "3.0"
services:
        hub:
                build:
                        context: ../../../..
                        dockerfile: core/net/examples/docker/hub.Dockerfile
                image: hub
        listener_1:
                build:
                        context: ../../../..
                        dockerfile: core/net/examples/docker/listener.Dockerfile
                image: listener
                depends_on:
                        - hub
        sender_1:
                build:
                        context: ../../../..
                        dockerfile: core/net/examples/docker/sender.Dockerfile
                image: sender
                depends_on:
                        - listener_1
