[package]
name = "ya-net"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ya-service-bus = { path = "../../service-bus/bus/" }
futures = "0.3"
actix-web = "1.0"
awc = "0.2.3"