[package]
name = "ya-net"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-service-bus = { path = "../../service-bus/bus/" }
ya-core-model = { path = "../model/" }

[dependencies.futures]
package="futures"
version="0.3"


[dev-dependencies]
actix = "0.9"