[package]
name = "ya-net"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-core-model = "0.1"
ya-service-bus = "0.1"

actix-web = "1.0"
awc = "0.2.3"
futures = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[dependencies.futures03]
package = "futures"
version = "0.3"
features = ["compat"]

[dev-dependencies]
actix = "0.8"