[package]
name = "ya-net"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-service-bus = "0.1"

futures = "0.1"

[dependencies.futures03]
package = "futures"
version = "0.3"
features = ["compat"]

[dev-dependencies]
actix = "0.8"