[package]
name = "ya-net"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
ya-service-bus = { path = "../../service-bus/bus/" }
ya-core-model = { path = "../model/" }
futures = "0.1"
actix-web = "1.0"
awc = "0.2.3"

[dependencies.futures03]
package="futures"
version="0.3"
features=["compat"]

[dev-dependencies]
actix = "0.8"