[package]
name = "ya-net"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
ya-core-model = { path = "../model/" }
ya-service-bus = "0.2"

[dependencies.futures]
package = "futures"
version = "0.3"


[dev-dependencies]
actix = "0.9"
